set COSMOS_KEY=%COSMOSDB_API_KEY%
set COSMOS_URI=%COSMOSDB_URI%
set COSMOS_DATABASE=DocAIDatabase
set COSMOS_CONTAINER=EmailExtracts
set COGNITIVE_SERVICE_KEY=%ALL_AI_SERVICES_API_KEY%
set COGNITIVE_SERVICE_ENDPOINT=%ALL_AI_SERVICES_ENDPOINT%
set BING_KEY=%BING_API_KEY%
set BING_QUERY_COUNT=3
set OPENAI_API_ENDPOINT=%OPENAI_API_ENDPOINT%
set OPENAI_API_KEY=%OPENAI_API_KEY%
set OPENAI_API_MODEL=%OPENAI_API_MODEL%

