set BLOB_STORE_SAS_TOKEN=%BLOB_STORE_SAS_TOKEN%

set COSMOS_KEY=%COSMOSDB_API_KEY%
set COSMOS_URI=%COSMOSDB_URI%
set COSMOS_DATABASE=DocAIDatabase
set COSMOS_CONTAINER=EmailExtracts
set COSMOS_CONTAINER_DEMOS=DocAIDemos

set COGNITIVE_SERVICE_KEY=%AI_VISION_SERVICE_API_KEY%
set COGNITIVE_SERVICE_ENDPOINT=%AI_VISION_SERVICE_ENDPOINT%

set ALL_AI_SERVICES_API_KEY=%ALL_AI_SERVICES_API_KEY%
set ALL_AI_SERVICES_ENDPOINT=%ALL_AI_SERVICES_ENDPOINT%
set BING_KEY=%BING_API_KEY%
set BING_QUERY_COUNT=3

set OPENAI_API_ENDPOINT=%OPENAI_API_ENDPOINT%
set OPENAI_API_KEY=%OPENAI_API_KEY%
set OPENAI_API_ENGINE=%OPENAI_API_ENGINE%
set OPENAI_API_VERSION=%OPENAI_API_VERSION%

set OPENAI_VISION_API_ENDPOINT=%OPENAI_VISION_API_ENDPOINT%
set OPENAI_VISION_API_KEY=%OPENAI_VISION_API_KEY%
set OPENAI_VISION_API_ENGINE=%OPENAI_VISION_API_ENGINE%
set OPENAI_VISION_API_VERSION=%OPENAI_VISION_API_VERSION%
set OPENAI_VISION_VIDEO_INDEX=%OPENAI_VISION_VIDEO_INDEX%
set AI_VIDEO_API_VERSION=%AI_VIDEO_API_VERSION%

set DOCAI_APP_TENANT_ID=%DOCAI_APP_TENANT_ID%
set DOCAI_APP_CLIENT_ID=%DOCAI_APP_CLIENT_ID%
set DOCAI_APP_CLIENT_SECRET=%DOCAI_APP_CLIENT_SECRET%
set DOCAI_EMAIL_SENDER_USER_NAME=%DOCAI_EMAIL_SENDER_USER_NAME%
set DOCAI_EMAIL_SENDER_PASSWORD=%DOCAI_EMAIL_SENDER_PASSWORD%
set DOCAI_EMAIL_RECEIVER_ADDRESS=%DOCAI_EMAIL_RECEIVER_ADDRESS%
set DOCAI_EMAIL_SUBJECT_PREFIX=%DOCAI_EMAIL_SUBJECT_PREFIX%